services:
  phonebook:
    build: .
    ports:
      - "8080:80"
    environment:
      PHONEBOOK_AUTH_LDAP: "ldap://10.10.10.2"
      PHONEBOOK_DOMAIN_PREFIX: "ALMATYTRADE"
      PHONEBOOK_DIR_LDAP: "172.16.65.2"
      PHONEBOOK_DIR_BASE_DN: "dc=almatytrade,dc=kz"
      PHONEBOOK_DIR_LOGIN: "yerzhan.abduhaimov@almatytrade.kz"
      PHONEBOOK_DIR_PASSWORD: "${PHONEBOOK_DIR_PASSWORD:?PHONEBOOK_DIR_PASSWORD is required, set it in .env}"
    restart: unless-stopped
